import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { LibraryService, Book, User } from './library.service';
@Component({ standalone: true, imports: [FormsModule, RouterLink], template: `<h1>Admin</h1><h2>Knjige</h2><ul class="admin-book-list">@for (book of books; track book.id) {<li class="admin-book-row"><a [routerLink]="['/books', book.id]">{{ book.title }}</a><button type="button" (click)="remove(book.id)" [attr.aria-label]="'Obriši knjigu ' + book.title">Obriši</button></li>}</ul><h2>Dodaj knjigu</h2><form (ngSubmit)="add()" aria-label="Dodavanje knjige"><label for="admin-title">Naslov</label><input id="admin-title" name="title" placeholder="Naslov" [(ngModel)]="data.title" required><label for="admin-author">Autor</label><input id="admin-author" name="author" placeholder="Autor" [(ngModel)]="data.author" required><label for="admin-isbn">ISBN</label><input id="admin-isbn" name="isbn" placeholder="ISBN" [(ngModel)]="data.isbn" required><label for="admin-description">Opis</label><textarea id="admin-description" name="description" placeholder="Opis" [(ngModel)]="data.description" required></textarea><label for="admin-image">Slika knjige</label><input id="admin-image" name="image" type="file" accept="image/*" (change)="selectImage($event)"><button type="submit">Dodaj</button></form>@if (message) {<p class="error-message" role="alert" aria-live="assertive">{{ message }}</p>}<h2>Svi korisnici</h2><ul class="admin-book-list" aria-label="Svi korisnici">@for (user of users; track user.id) {<li class="admin-book-row"><span>{{ user.username }}</span><button type="button" (click)="removeUser(user.id)" [attr.aria-label]="'Obriši korisnika ' + user.username">Obriši</button></li>}</ul>` })
export class AdminComponent {
	private library = inject(LibraryService); books: Book[] = []; users: User[] = []; message = ''; selectedImage?: File;
	data = { title: '', author: '', isbn: '', description: '' };
	constructor() { this.load(); this.library.adminUsers().subscribe(users => this.users = users); }
	load() { this.library.books().subscribe(books => this.books = books); this.library.adminUsers().subscribe(users => this.users = users); }
	selectImage(event: Event) { this.selectedImage = (event.target as HTMLInputElement).files?.[0]; }
	add() { const form = new FormData(); Object.entries(this.data).forEach(([key, value]) => form.append(key, value)); if (this.selectedImage) form.append('image', this.selectedImage); this.library.addBook(form).subscribe({ next: () => { this.message = 'Knjiga dodata.'; this.data = { title: '', author: '', isbn: '', description: '' }; this.selectedImage = undefined; this.load(); }, error: error => this.message = error.error?.message ?? 'Greška.' }); }
	remove(id: number) { this.library.deleteBook(id).subscribe({ next: () => this.load(), error: error => this.message = error.error?.message ?? 'Brisanje knjige nije uspelo.' }); }
	removeUser(id: number) { this.library.deleteUser(id).subscribe({ next: () => this.load(), error: error => this.message = error.error?.message ?? 'Brisanje korisnika nije uspelo.' }); }
}