services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: sqlite:////data/library.db
    volumes:
      - library_data:/data
      - book_covers:/app/static/book-covers

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  library_data:
  book_covers: